### ISSUE TITLE
appIdentity contains incorrect ID and Version

### ISSUE THREAD

**Issue by aal80** [ibm-bluemix-mobile-services/bms-clientsdk-swift-security#11]
After successful obtainAuthorization:
appIdentity.ID always equals Optional("org.cocoapods.BMSSecurity")
appIdentity.Version always equals 1.0

ID should return the bundleId of iOS app
version should return the version of iOS app

**Comment by vitalymibm** [comment]
@AntonAleksandrov 
Fixed and released v2.0.2

Note that imp.application properties returned with id_token will be fixed as part of another issue.
