### ISSUE TITLE
JSON represented as [String: AnyObject] in Swift 3

### ISSUE THREAD

**Issue by AnthonyOliveri** [ibm-bluemix-mobile-services/bms-clientsdk-swift-security#8]
There are methods that accept [String: AnyObject] as the parameter type. This works for Swift 2, but in Swift 3, it is more appropriate (and safer) to represent JSON as [String: Any] to avoid potentially erroneous casting to AnyObject from non-class types (like String and Error). I noticed this in the submitAuthenticationFailure, submitAuthenticationChallengeAnswer, onAuthenticationSuccess, and onAuthenticationFailure methods. There may be other methods/properties where this is occurring.

**Comment by vitalymibm** [comment]
@AntonAleksandrov Do we want to make this refactoring (yes, there are many places where we represent JSON as [String: AnyObject] beside the above mentioned methods) NOW?

**Comment by aal80** [comment]
@vitalymibm yes, Swift2 SDK should be using AnyObject, Swift3 should be using Any. I consider this a defect.

**Comment by odedBetzalel** [comment]
Fixed.
