### ISSUE TITLE
getUserIdentityFromToken always returns nil

### ISSUE THREAD

**Issue by tfrank64** [ibm-bluemix-mobile-services/bms-clientsdk-swift-security#9]
I'm trying to login with my iOS app and in the process, I call the `obtainAuthorization` method on the `AuthorizationManager` object. I was getting an error so that `.userIdentity.ID` was always nil when it used to work just fine before the Swift 3 upgrade. I traced the problem to the `getUserIdentityFromToken` method and it seems the conversion of the `Data` object to a `String` always fails for both `NSString` and `String`. It fails [here](https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-swift-security/blob/master/Source/mca/internal/AuthorizationProcessManager.swift#L247). I'm unsure of why this is or if I'm getting an invalid idToken. Thanks for the help.

**Comment by vitalymibm** [comment]
The problem has been fixed. I published v2.0.1 of BMSSecurity. Please try it.

**Comment by tfrank64** [comment]
Awesome, seems to work well.
Also, if you care, there are redundant `String(data: decodedIdTokenData, encoding: String.Encoding.utf8)` calls [here](https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-swift-security/blob/master/Source/mca/internal/AuthorizationProcessManager.swift#L247). Doesn't change functionality though.

Thanks for this fix.

**Comment by vitalymibm** [comment]
You welcome. 
I know about redundant calls :(. This code is not written by me and the developer is on vacations. So I don't want to change anything without asking him (maybe there was some reason behind this logic, because it was here before conversion to Swift 3).

**Comment by tfrank64** [comment]
Ah, that makes sense. I'm not too worried about it 😄
